server:
  port: 8800

  
resilience4j.circuitbreaker:
  configs:
    default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10 # {통계건수}
        minimumNumberOfCalls: 2 # {최소요청횟수} 
        failureRateThreshold: 60 # {실패율} 
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 5s # {Circuit Breaker유지시간}         
        eventConsumerBufferSize: 10
  instances:
    mycb:
        baseConfig: default
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true    

api:
  mon:
    url: http://localhost:8322/

router:
  global:
    service: 
      url: http://localhost:8088

logging: 
  level.org.springframework.cloud.gateway: info
  reactor.netty: info



